### ISSUE TITLE
[Bug]: Ethiopia - After the collapse of the Italian East Africa, there will be 2 Addis Ababa victory points overlapped onto each other.

### ISSUE THREAD

**Issue by questbird** [TNODevs/TNO-Bug-Tracker#3417] opened 2024-07-16 09:23 UTC
### Operating System

Windows 11

### HOI4 version

1.14.7

### TNO version

1.5.0d

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

After the collapse of the Italian East Africa, there will be 2 Addis Ababa victory points overlapped onto each other. Sorry for bad english but this short description speaks for itself.

### Steps to reproduce / Cause of the issue

1. Wait for the collapse of Italian East Africa
2. Then find the state of Addis Ababa when Ethopia controls it
3. That is the bug

### Expected behaviour

2 Addis Ababa victory points overlapped onto each other, 1 the capital of the country 1 isnt

**Comment by runelead00** [comment] 2024-07-16 16:28
Duplicate of #2967, will be fixed with ODF integration

**Closed by runelead00** 2024-07-16 16:28 UTC
Labels: Bug
