### ISSUE TITLE
England - Impossible to remain neutral in "An Atlantic Battleground" event chain due to no monthly influence gain as England

### ISSUE THREAD

**Issue by doctorrandomiise** [TNODevs/TNO-Bug-Tracker#354] opened 2021-11-30 00:50 UTC
- Operating System: Windows 10
- HOI4 Version: 1.10.8
- TNO Version: 1.20.d
- Any other mods in use: None
- Were you using Steam? Yes.
- Which expansions do you NOT have? The two most recent DLCs.

**Longer Description of Issue:**

I'm playing as England, and I've reached the _"An Atlantic Battleground"_ event chain. I quickly discovered that England has no monthly influence gain (regardless of what the value on the screen states), while the two superpowers do. This makes it effectively impossible to avoid joining a faction (even when playing as optimally as possible) as England has such an overwhelming disadvantage in its ability to gain influence.

I couldn't reach the _"Reveal Our Motive"_ focus through normal gameplay without failing the event chain, so I used _Focus.AutoComplete_ to blitz to it; however, the 180 day timer after completing the focus before England's neutrality is guaranteed means it will inevitably be forced into a faction. So, I tried cheating my way to the _"A Great Britain"_ focus using _Focus.NoChecks_ to ignore the requirements but with no luck, as the "_An Atlantic Battleground"_ event chain can only be cancelled by running out the timer. This bug completely ruins my immersion, and I really can't continue with this playthrough unless it is resolved- so, until the bug is patched, please do tell me if there is any command I can use or manual edit I can make to a save file that will allow me to play the game as intended. Thanks.

**Screenshots:**

![image](https://user-images.githubusercontent.com/95258140/143963117-6472cb7d-76d5-46e2-9f4a-a97d68ab6fe6.png)
Date: 31 May 1968
American Influence: 26
American Monthly Influence Gain: 0
German Influence: 24
German Monthly Influence Gain: 2
England's Influence: 27.75
England's Monthly Influence Gain: 2

![image](https://user-images.githubusercontent.com/95258140/143963155-701bf8e9-e27d-4fed-b7e4-d706b8e9649d.png)
Date: 1 June 1968
American Influence: 26
American Monthly Influence Gain: 0
German Influence: 26
German Monthly Influence Gain: 2
England's Influence: 27.75
England's Monthly Influence Gain: 2

**Comment by masterbobli** [comment] 2021-12-02 05:55
The issue is a duplicate of #237 and has been fixed in dev build. Thanks for reporting.

**Closed by masterbobli** 2021-12-02 05:55 UTC
Labels: Bug, Duplicate
