### ISSUE TITLE
The problem decision of KDM

### ISSUE THREAD

**Issue by LuKunwei** [TNODevs/TNO-Bug-Tracker#3376] opened 2024-07-02 10:15 UTC
### Operating System

Windows11

### HOI4 version

1.14.7.f4d3(f03b)

### TNO version

1.5.0d

### Do you have other mods in use?

The New Order: Last Days of Europe(CN.Ver)

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[KOM_1970_10_19_20_temp.zip](https://github.com/user-attachments/files/16066091/KOM_1970_10_19_20_temp.zip)

### Describe the bug

TYM created the Communist International as the leader of the camp, and pulled KDM into the camp, and KDM became a full member. Subsequently, KDM peacefully annexed TYM through diplomatic means, but at this time, the Communist International was voting on a resolution, and TYM was annexed before the vote, resulting in the voting was stuck and other resolutions could not be voted on.

### Steps to reproduce / Cause of the issue

1. Let TYM create the Comintern
2. Use KDM to annex TYM at the time of the general Assembly vote
3. See the error

### Expected behaviour

When the Comintern votes, if TYM is annexed by KDM without voting, then: 1. Automatically counted as TYM abstention, and then popped out the event: election of the new chair of the Comintern, and selection of the new chair through a series of simple diplomatic games; 2. Or cancel the vote on the resolution directly, and put it back in the resolution column for a period of time, and then vote again, and the new chair country will default to the country with the strongest comprehensive strength.

### Screenshots

![屏幕截图 2024-07-02 181238](https://github.com/TNODevs/TNO-Bug-Tracker/assets/135266714/7507b672-7216-4221-8ac0-e87e03f6518b)

**Comment by Marok132** [comment] 2024-07-04 10:55
This a general issue for each tag who creates COMECON first, not only TYM.

**Comment by runelead00** [comment] 2024-07-05 19:48
Duplicate of #2107

**Closed by runelead00** 2024-07-05 19:48 UTC
Labels: Bug
