### ISSUE TITLE
HAI- Cantave suddenly disappeared

### ISSUE THREAD

**Issue by otherside02** [TNODevs/TNO-Bug-Tracker#2863] opened 2023-11-29 14:16 UTC
### Operating System

Windows10

### HOI4 version

V1.13.5

### TNO version

v1.5.0b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

After Cantave came to power, after a period of time, Cantave suddenly disappeared
![捕获43](https://github.com/TNODevs/TNO-Bug-Tracker/assets/46292981/44a5c787-03b1-4ccf-8eb8-506a5c220066)

### Steps to reproduce / Cause of the issue

1.Make Cantave came to power
2.after a period of time

### Expected behaviour

So Cantave doesn't suddenly disappear

**Comment by otherside02** [comment] 2023-11-29 14:17
Also, there's a bug in Haiti that I want you to take a look at
https://github.com/TNODevs/TNO-Bug-Tracker/issues/2607

**Comment by runelead00** [comment] 2023-11-30 08:30
Duplicate of #2835

**Closed by runelead00** 2023-11-30 08:30 UTC
Labels: Bug
