### ISSUE TITLE
Afghanistan - Tver Republic cores Herat state

### ISSUE THREAD

**Issue by Astronaut1337** [TNODevs/TNO-Bug-Tracker#368] opened 2021-12-02 04:51 UTC
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.5/8
- TNO Version: Initial hotfix for Toolbox Theory
- Any other mods in use: Radio TNO, The New Order: Last Waltz of Europe, The Second West Russian War
- Were you using Steam? Yes
- Which expansions do you NOT have? La Resistance, Battle for the Bosphorous

**Longer Description of Issue:**

After the collapse of RK Moskowien during the GCW, Bronislav Kaminski's fascist breakaway state, the Tver Republic, gains a permanent core on the Afghan state of Herat. This isn't a major gameplay issue per se, but it is very strange and slightly amusing. 
**Steps to Reproduce/Cause Issue:**

1. Begin a TNO game

2. Wait for the collapse of RK Moskowien

3. Check the cores on Herat

**Screenshots:**
![image](https://user-images.githubusercontent.com/45863284/144359196-e73f9d8e-e29f-4a50-8a93-5bf2168436ae.png)
![image](https://user-images.githubusercontent.com/45863284/144359229-e9e6983a-d61c-46ab-8de5-ede65bb50f8b.png)

**Comment by masterbobli** [comment] 2021-12-02 05:44
A duplicate of #260. It has already been fixed. Thanks for reporting

**Closed by masterbobli** 2021-12-02 05:44 UTC
Labels: Map, Duplicate
