### ISSUE TITLE
USA - Wallace. Unending SAW, Indonesian war started but undeclared.

### ISSUE THREAD

**Issue by mstachife-dot** [TNODevs/TNO-Bug-Tracker#1129] opened 2022-10-15 15:58 UTC
### Operating System

Windows 10

### HOI4 version

1.12.3

### TNO version

1.3.0a

### Do you have other mods in use?

Radio TNO: Music of the New Order

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Files

Save game: 

[USA_1967_07_20_11.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/9792717/USA_1967_07_20_11.zip)

### Describe the bug

SAW won with south africa taking all territory, event to trigger mandates doesnt fire. 

Indonensian war event and response decisions popped up, war seemingly never started.

### Steps to reproduce / Cause of the issue

Load up save

### Expected behaviour

SAW to finish, Indonesian war to start

### Screenshots

SAW: 
![Screenshot (22)](https://user-images.githubusercontent.com/53803662/195996010-a9f73caa-0cf7-429a-8639-76558d0e0060.png)

Indonesia:
![Screenshot (23)](https://user-images.githubusercontent.com/53803662/195996017-8e27d14b-52c1-4d16-9305-ba52b72aba7e.png)

### Additional information

SAW ended during treaty port conference, may be relevant.

**Comment by sp1r3e** [comment] 2022-10-15 19:27
Had the same thing happen to me, but I wasn't in the middle of treaty port negotiations so I don't think that's what caused it. I also had the no volunteer supply bug as well.

**Comment by cookieacid** [comment] 2022-10-16 02:12
Same problem, treaty port negotiations hadn't started either. (The volunteer supply bug isn't caused by TNO its a bug in the HOI4 update. To fix just use console: allowdiplo and yesman then ask South Africa for military access.)

**Comment by runelead00** [comment] 2022-10-16 21:03
Fixed in Current Release
- also Indonesia is WAD, Indonesia shatters before open warfare begins

**Closed by runelead00** 2022-10-16 21:03 UTC
Labels: Bug
