### ISSUE TITLE
All Countries- When I click the button to choose where my divisions should be deployed my game crashes

### ISSUE THREAD

**Issue by SilverFoxGOC** [TNODevs/TNO-Bug-Tracker#679] opened 2022-02-22 17:49 UTC
**Questions**

- Operating System: Windows
- HOI4 Version: 1.11.1
- TNO Version: Latest
- Any other mods in use: FPS Map (already tried without it, not the problem. 10k Exp Limit. FPS Boost by Harvey (as substitute for FPS Map. Not the problem too as I tried without that mod.) Radio TNO and 2WRW
- Were you using Steam? No
- Which expansions do you NOT have? have all of them

When I try to train divisions, I have to choose where they spawn on the green lines map.. But once I press the "chose province" button beneath the division, the game crashes after a few seconds.

1. Open Game

2. Choose any nation

3. Try to train a division and deply it..

**Comment by Stormeagle449** [comment] 2022-12-01 10:31
Duplicate of #667, most likely fixed already.

**Closed by Stormeagle449** 2022-12-01 10:31 UTC
Labels: Crash, Duplicate
