### ISSUE TITLE
Chile-Elections Event-Military Coup

### ISSUE THREAD

**Issue by DuceMewtwo** [TNODevs/TNO-Bug-Tracker#3640] opened 2024-10-11 19:07 UTC
### Operating System

Windows 10

### HOI4 version

Last

### TNO version

Last

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

I No Have Now

### Describe the bug

No event has happened since Alessandri's resignation and successor, in addition to the [Liberal-Congress] elections.

### Steps to reproduce / Cause of the issue

Before the last update [Mexico-11-10-2014 now] the events did happen

### Expected behaviour

that the election events happened

### Screenshots

i dont have

### Additional information

Only the events of the war with Argentina and derivatives happen

**Comment by runelead00** [comment] 2024-10-13 19:44
Duplicate of #3527

**Closed by runelead00** 2024-10-13 19:44 UTC
Labels: Bug
