### ISSUE TITLE
Omsk - Military Factories will not enter Production Menu

### ISSUE THREAD

**Issue by H-Web-Droid-Frac** [TNODevs/TNO-Bug-Tracker#566] opened 2022-01-27 23:59 UTC
**Questions**

- Operating System: Windows 10
- HOI4 Version: Barbarossa v1.11.5.5b4f (0200)
- TNO Version: TNO v1.2.1 - Toolbox Theory NSB Patch
- Any other mods in use: No Other Mods Active
- Were you using Steam? Yes
- Which expansions do you NOT have? I have all DLC

**Longer Description of Issue:**
- Started playing Omsk, everything working perectly untill I realize that production isn't working. After Reloading the save and turning off all Mods and Custom Game Rules, it still wasn't working. Ater trying a few more times, and closing and opening hoi4, it still didn't budge. I am unsure if it affects civs or all countries.

**Screenshots:**
![Screenshot (17)](https://user-images.githubusercontent.com/74271226/151462983-64b8517b-8dc1-41e2-9515-909a7870d2db.png)
![Screenshot (18)](https://user-images.githubusercontent.com/74271226/151463017-029b2234-c193-4d7f-93e7-373b4088ccbc.png)
![Screenshot (19)](https://user-images.githubusercontent.com/74271226/151463028-45b9aa99-afa0-4361-8aa8-ba49a668b149.png)

**Comment by T3RR5V0N** [comment] 2022-01-28 20:00
i'm having the same issue. it affects all countries as far as i can tell, and apparently it's a problem because the 1.11.5 update.

**Comment by InvaderGirn** [comment] 2022-01-29 13:55
I am having the same thing effect me, making every nation unable to use Military and Civilian Factories. Originally however my game was fine, I can still load into my Vyatka game and its working as intended. however if I try to start any new games the bug persists even after completely re-downloading the mod.

**Comment by Scarsoftime** [comment] 2022-02-13 05:42
Fixed in the most recent update

**Closed by Scarsoftime** 2022-02-13 05:42 UTC
Labels: Bug
