### ISSUE TITLE
USA- Global Conflicts Section not displaying properly

### ISSUE THREAD

**Issue by Bubito2003** [TNODevs/TNO-Bug-Tracker#2022] opened 2023-06-27 19:01 UTC
### Operating System

Windows 11

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[Global Conflicts Error.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11925306/Global.Conflicts.Error.zip)

### Describe the bug

Whenever I go to Global Conflicts it does not display properly.

### Steps to reproduce / Cause of the issue

1. Play as USA
2. Wait until any Global Conflict starts
3. Go to Foreign Policy
4. Click Global Conflicts

### Expected behaviour

I don't know what causes this.

### Screenshots

![obraz_2023-06-27_202609345](https://github.com/TNODevs/TNO-Bug-Tracker/assets/137928295/60749829-7dda-4559-82d1-bc174b7fffbe)

![Zrzut ekranu 2023-06-29 194331](https://github.com/TNODevs/TNO-Bug-Tracker/assets/137928295/ff80ffe5-7579-4da6-9247-e7d367a617a0)
Can't choose the province
![Zrzut ekranu 2023-06-29 192049](https://github.com/TNODevs/TNO-Bug-Tracker/assets/137928295/32f18ec7-5e16-4aa2-abf6-6cd2d28b52a8)
Reconstruction failed...
### Additional information
Ugly American is the worst update :(

**Comment by runelead00** [comment] 2023-07-01 01:47
Can't reproduce, do you have a save or are using any submods enabled?

**Comment by Bubito2003** [comment] 2023-07-01 08:48
> 

I use Second West Russian War. Save uploaded.

**Comment by runelead00** [comment] 2023-07-02 03:28
issue related to submod, closing

**Closed by runelead00** 2023-07-02 03:28 UTC
Labels: Bug, Can't Reproduce, Needs Info
