### ISSUE TITLE
South Africa War OFN Victory not working

### ISSUE THREAD

**Issue by TheoMoseby** [TNODevs/TNO-Bug-Tracker#1230] opened 2022-10-19 23:37 UTC
### Operating System

Windows 11

### HOI4 version

1.12.3

### TNO version

1.3.0b

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

LAR, NSB, BBA

### Files

Github says it doesn't support HOI4 File

### Describe the bug

- 'event safwar.13' doesn't fire when all 3 Reichskommissariats collapse
- The death event (featuring the death quote of the nation) for the final reichskommissariat (Ostafrika in this instance) doesn't show up
- The Mandate nations don't spawn in
- The cores for COG and ANG do spawn in, but the cores for MZB don't, and the Ostafrika cores are still present
- When MZB is manually released after all cores are added, they start with no manpower or army experience
- Jones Savimbi is in-charge of the Angola mandate instead of John D. Lavelle (don't know if this is intentional)
- Game tends to crash whenever Angola finishes all of it's focuses (not always)
- East Africa finishes the bottom focus before finishing all of their focuses previously
- Unsure if the states in the second screenshot is for Mozambique or for the Union, East Africa still exists after finishing the bottom focus (No Zimbabwe spawns in)
- Angola doesn't join the OFN as an observer, still apart of the economic sphere
- The Africa is saved Super Event doesn't fire at all (unsure if it's meant too)

Screenshot included to help workaround the problem for the player

### Steps to reproduce / Cause of the issue

See first screenshot

### Expected behaviour

South Africa War OFN Victory event to fire when the 3 Reichskommissariats collapse, and the Mandates to spawn in

### Screenshots

![South African War Help](https://user-images.githubusercontent.com/116231011/196822122-fbef35aa-f75d-4641-8308-717e9bc9d59c.PNG)
![East Africa](https://user-images.githubusercontent.com/116231011/196823758-392c4d7f-a210-41c9-bc49-132d0db655bd.jpg)
![EA 2](https://user-images.githubusercontent.com/116231011/196823768-856ddd24-c7d4-42db-a828-569e9c8729eb.jpg)
![EA 1](https://user-images.githubusercontent.com/116231011/196823932-784b78f1-6fea-43e0-840e-d418cae12d8c.jpg)
![MA](https://user-images.githubusercontent.com/116231011/196823945-7054d1a3-5014-44d7-bc1a-ed121780b211.jpg)

**Comment by TheoMoseby** [comment] 2022-10-19 23:38
![JS](https://user-images.githubusercontent.com/116231011/196824354-08aa3879-bd7a-475d-b23f-78d5abbad34f.jpg)
Jonas in charge of Angola

**Comment by runelead00** [comment] 2022-10-31 23:31
SAW peace fixed in Dev Build by Curvinghawk, most of other bugs caused by broken peace deal

**Closed by runelead00** 2022-10-31 23:31 UTC
Labels: Bug
