### ISSUE TITLE
ROM - Missing Title & Description for "Michael The Brave" Spirit

### ISSUE THREAD

**Issue by Blanker389** [TNODevs/TNO-Bug-Tracker#3222] opened 2024-04-30 01:41 UTC
### Operating System

Windows 11

### HOI4 version

1.14.5

### TNO version

1.5.0c

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TOA

### Files

[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/15156664/game.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/15156667/error.log)
[TNO.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/15156673/TNO.zip)

### Describe the bug

The spirit that should be "Michael The Brave" pops up as "ROM_michael_the_brave" and is without any description.

### Steps to reproduce / Cause of the issue

1. Start TNO.
2. Click on Romania.
3. Hover over Michael The Brave spirit.
4. Observe issue.

### Expected behaviour

Shows as "Michael The Brave" and has description.

### Screenshots

<img width="245" alt="image" src="https://github.com/TNODevs/TNO-Bug-Tracker/assets/98370487/36722898-e39d-4b51-8ded-f3943e14479b">

**Comment by runelead00** [comment] 2024-05-03 20:58
Duplicate of #3048

**Closed by runelead00** 2024-05-03 20:58 UTC
Labels: Bug
