### ISSUE TITLE
WOL&FFR - The game crashed at the end of the West African war

### ISSUE THREAD

**Issue by otherside02** [TNODevs/TNO-Bug-Tracker#1394] opened 2022-11-10 10:13 UTC
### Operating System

Windows10

### HOI4 version

1.12.5

### TNO version

v1.3.0d

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10151863/error.log)

### Describe the bug

When I defeated Cameroon in the West African War of 1966, the game crashed

### Steps to reproduce / Cause of the issue

1.start the West African War of 1966 (WAA vs FMA vs PALF )
2.play Wolofia (or other countries in the West African Alliance)/Free France, defeated Cameroon
3.game crashed

### Expected behaviour

The game is running properly

### Screenshots

![捕获144](https://user-images.githubusercontent.com/46292981/201063348-eee4337c-3252-4a5a-bad0-cb2552c217ae.PNG)
![20221110174656_1](https://user-images.githubusercontent.com/46292981/201063482-e544c182-8ab8-45d7-9bbc-d350a4ce4b81.jpg)

**Comment by runelead00** [comment] 2022-12-04 07:28
Without a save or error log, we can't track down the cause of the crash

**Comment by otherside02** [comment] 2022-12-04 13:48
> Without a save or error log, we can't track down the cause of the crash

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/10148623/error.log)
error log is here

**Comment by runelead00** [comment] 2023-01-31 18:22
Should be fixed for SD by Oveja

**Closed by runelead00** 2023-01-31 18:22 UTC
Labels: Bug, Needs Info
