### ISSUE TITLE
All Countries- Game crashes at start

### ISSUE THREAD

**Issue by Cosaccia** [TNODevs/TNO-Bug-Tracker#1127] opened 2022-10-15 15:39 UTC
### Operating System

Windows 11

### HOI4 version

1.12

### TNO version

1.3

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, NSB, BBA

### Files

[memory.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9792383/memory.log)
[message.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9792384/message.log)
[posted_commands.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9792385/posted_commands.log)
[random.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9792386/random.log)
[received_commands.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9792387/received_commands.log)
[sent_commands.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9792388/sent_commands.log)
[setup.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9792389/setup.log)
[system.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9792390/system.log)
[system_debug.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9792391/system_debug.log)
[text.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9792392/text.log)
[time.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9792393/time.log)
[ai.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9792394/ai.log)
[ai_trace.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9792395/ai_trace.log)
[code_revisions.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9792396/code_revisions.log)
[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9792397/error.log)
[executed_commands.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9792398/executed_commands.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9792399/game.log)
[graphics.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/9792400/graphics.log)
(All my logs from today)

### Describe the crash

I go to the opening menu. I click single player, new game, and I get to choosing the country I want to play as. I choose it. I start the game. Once it has loaded, the game will crash within a few seconds, without me unpausing.

### Steps to reproduce / Cause of the crash

1. Go to the opening menu.
2. Select Singleplayer.
3. Select new game.
4. Select 1962.
5. Select country.
6. Start.
7. The game loads.
8. After it has finished loading, it will simply crash after a few seconds.

### Additional information

This has been going on essentially since Barbarossa came out.

**Comment by runelead00** [comment] 2022-10-18 19:42
Duplicate of #962, see there for potential solution

**Closed by runelead00** 2022-10-18 19:42 UTC
Labels: Crash
