### ISSUE TITLE
USA - There is old lore description from the 'What Could Have Been' event

### ISSUE THREAD

**Issue by Ikidikid** [TNODevs/TNO-Bug-Tracker#3327] opened 2024-06-23 00:05 UTC
### Operating System

Windows 10 Enterprise

### HOI4 version

1.14.6

### TNO version

1.5.0d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

In the event description of 'What Could Have Been', I saw some of the old lore reference instead of putting the new lore.  

### Steps to reproduce / Cause of the issue

1. Play as USA.
2. Elect Bennett. 

### Expected behaviour

Probably, oversight.

### Screenshots

![Image_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/131833099/760cb940-17aa-4e34-b57f-b80b56251fac)

**Comment by Stormeagle449** [comment] 2024-06-23 20:13
Duplicate of issue #1275

**Closed by Stormeagle449** 2024-06-23 20:13 UTC
Labels: Localization, Duplicate
