### ISSUE TITLE
USA - Possible cause of the infamous FOPO lag

### ISSUE THREAD

**Issue by Vehuga** [TNODevs/TNO-Bug-Tracker#2418] opened 2023-10-08 15:58 UTC
### Operating System

Windows 10 Home

### HOI4 version

Avalanche v.1.12.14

### TNO version

The Ruin 1.5.0

### Do you have other mods in use?

Modifier Icons (TNO Version), TNO: Last Waltz Expanded

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

BBA

### Describe the bug

I'm aware that many people have already submitted reports on this problem, but there is a partial fix for this. Part of the reason for the infamous lag is a duplicate function for the animated bar used in the Haitian Civil War in "TNO_foreign_policy_custom.gfx ". From personal experience, the lag doesn't kick in until the Madagascar or Haitian proxy conflicts, so this is the most likely reason for the unbearable lag.  Removing the incorrect duplicate function didn't fix the lag completely, but at least it no longer carries over when you close the Foreign Policy window.

### Steps to reproduce / Cause of the issue

1. Open “TNO_foreign_policy_custom.gfx” under “\interface\proxy_mechanics”
2. Scroll down to line 863
3. Notice that this is a duplicate function of another function. The duplicate also uses an incorrect number of frames, which was supposed to be 4 frames
4. Delete the duplicate function

### Expected behaviour

The lag should be reduced when you close the FOPO, if implemented.

### Screenshots

![FOPOLag](https://github.com/TNODevs/TNO-Bug-Tracker/assets/139922220/d2cc6581-bd04-4d4b-9ca3-a2744f9d3705)
![FOPOLag2](https://github.com/TNODevs/TNO-Bug-Tracker/assets/139922220/c0d119d7-757d-4d95-b80f-c58832731e48)

**Comment by runelead00** [comment] 2023-10-09 00:40
This is with almost certainty not the cause of the lag, but Fixed in Dev Build

**Closed by runelead00** 2023-10-09 00:40 UTC
Labels: Bug
