### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by GayBullfrog** [TNODevs/TNO-Bug-Tracker#3067] opened 2024-03-14 23:59 UTC
### Operating System

Windows 11

### HOI4 version

1.14.2

### TNO version

1.5.0

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

MTG, NSB, BBA, AAT, TOA

### Describe the bug

Playing as any nation, (Japan, USA, Germany etc.) when proxy wars start, I can send volunteers and it will initially show the correct amount of volunteers I am able to send. This will change when I attempt to send that amount of volunteers and it will only show 1 volunteer available. This will persist through the entire proxy and will not go away when I select decisions or focuses that allow more volunteers to be sent.

### Steps to reproduce / Cause of the issue

1. Start a proxy war as a major nation
2. Click the send volunteers button
3. Select the amount of divisions that can be sent
4. Click on the send volunteers button

### Expected behaviour

The initial amount of divisions allowed will revert to 1 and remain there.

### Additional information

This bug has existed for me on previous versions, with and without the DLCs

**Comment by runelead00** [comment] 2024-03-22 05:44
Duplicate of #1212

**Closed by runelead00** 2024-03-22 05:44 UTC
Labels: Bug, Duplicate
