### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by Falconinglasses** [TNODevs/TNO-Bug-Tracker#1921] opened 2023-06-04 17:13 UTC
### Operating System

Win10

### HOI4 version

12.13

### TNO version

1.4.1c

### Do you have other mods in use?

rusification und community expansion

### Were you using Steam?

No

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, NSB, BBA

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/11646215/error.log)

### Describe the crash

Randomly happens when some event comes up on screen, or sometimes just on its own

### Steps to reproduce / Cause of the crash

Play
Get f*cked randomly

**Comment by runelead00** [comment] 2023-06-04 18:56
Duplicate of #1922

**Closed by runelead00** 2023-06-04 18:56 UTC
Labels: Crash, Duplicate
