### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by cooldog234** [TNODevs/TNO-Bug-Tracker#2874] opened 2023-12-06 00:43 UTC
### Operating System

Windows 10

### HOI4 version

1.13.5

### TNO version

v1.5.0b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

LAR

### Describe the bug

Playing as West Russian Revolutionary Front, in the Comintern voting panel the vote is stuck on "Provide Military Aid for the East Siberian Soviet Republic" however, the war between the Central Siberian Republic and the East Siberian Republic has ended in the East's favor, and even after Unification the vote is still stuck on providing Military Aid. 

### Steps to reproduce / Cause of the issue

Play as West Russian Revolutionary Front, join COMECON, war between East and Central Siberia, vote appears in voting panel for military aid. 

### Expected behaviour

I expected the vote to either pass, or be phased out of the voting window after the war ended 

### Additional information

This might've just been a once off issue with how events took place, however I thought I should mention it regardless

**Comment by runelead00** [comment] 2023-12-13 06:42
duplicate of #2107

**Closed by runelead00** 2023-12-13 06:42 UTC
Labels: Bug
