### ISSUE TITLE
Republic of Finland - Game crashes

### ISSUE THREAD

**Issue by Jaeger56** [TNODevs/TNO-Bug-Tracker#2169] opened 2023-08-31 17:08 UTC
### Operating System

Windows 11

### HOI4 version

1.12.14.50e

### TNO version

1.4.1d

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/12488518/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/12488522/game.log)

### Describe the crash

It simply throws me to my desktop, no freezing.

### Steps to reproduce / Cause of the crash

Not sure. I did not do anything special before it.

### Additional information

I really am no expert in these things but what little i understand from the logs the crash has something to do with the event murmansk.5 and finnish division templates. For extra context: i was playing as Finland and had already capitulated Murmansk and was fighting West Russia at the time of the crash, i had also deleted all of the division templates i was not using so that might effect it as well. A lot of Finlands skeleton content was pretty broken throughout my playthrough, i know that it is not meant to be played but oh well. Sorry if this report was not constructed very well, i am an amateur with these things :)

**Comment by runelead00** [comment] 2023-09-01 17:35
Fixed in Dev Build, caused by deleting division templates

**Closed by runelead00** 2023-09-01 17:35 UTC
Labels: Crash
