### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by Chugwugg** [TNODevs/TNO-Bug-Tracker#3434] opened 2024-07-30 06:52 UTC
### Operating System

Windows 11

### HOI4 version

Bolivar v1.14.7.f4d3 (f03b)

### TNO version

v1.5.0d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

AAT, TOA

### Files

[error.log](https://github.com/user-attachments/files/16423355/error.log)

### Describe the crash

When playing as the NPA, the game randomly crashes after I cap Northern ROC during the Great Asian War (in this case that was May 1967; I don't think the exact time is relevant so long as it's within late '67

### Steps to reproduce / Cause of the crash

Play in my savefile attached as the NPA and see whether you can finish the GAW (and see whether crash happens or not)

**Comment by runelead00** [comment] 2024-08-04 04:45
Duplicate of #3379, will be fixed next update temp solution listed there

**Closed by runelead00** 2024-08-04 04:45 UTC
Labels: Crash
