### ISSUE TITLE
West Russian Revolutionary Front - Blacked out 3D model.

### ISSUE THREAD

**Issue by Leon-Hooks** [TNODevs/TNO-Bug-Tracker#3121] opened 2024-04-04 21:35 UTC
### Operating System

Windows 10, 64-bit 

### HOI4 version

Bolivar v1.14.4.44c7 [713f][S]

### TNO version

1.5.0c - "The Ruin"

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TOA

### Describe the GFX issue

Blacked out 3d model for the culture primary infantry unit 3D model. Completely without textures, aside from the weapon model.

### Steps to reproduce / Cause of the issue

1. Load up the game
2. Select WRRF
3. Start Game
4. Perceive Irregularity 

### Expected behaviour

I Anticipated the model for the units to have textures. 

### Screenshots

https://steamuserimages-a.akamaihd.net/ugc/2499009029551862198/410E237F40F5B1CFD5C274459F4581B460862ABE/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false

### Additional information

Not a game breaking bug, just a mild nuisance. Appreciate you.

**Comment by runelead00** [comment] 2024-04-07 20:23
Duplicate of #2522

**Closed by runelead00** 2024-04-07 20:23 UTC
Labels: GFX/Graphics, Duplicate
