### ISSUE TITLE
Turkestan Legion under Korsirmat - Missing economy minister

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#992] opened 2022-09-16 16:21 UTC
### HOI4 version

1.11.13

### TNO version

1.2.1c

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, LAR, NSB

### List the loc issues below

1. 
![Screenshot (1067)](https://user-images.githubusercontent.com/98137316/190684898-acd33877-cf6b-4212-a2ea-01c780d993a7.png)

**Comment by runelead00** [comment] 2022-09-16 17:26
Duplicate of #840 you don't need to report the same bug 4 times

**Closed by runelead00** 2022-09-16 17:26 UTC
Labels: Localization, Duplicate
