### ISSUE TITLE
Bhutan - Minister portrait issue

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#1250] opened 2022-10-21 20:41 UTC
### Operating System

Windows 11

### HOI4 version

1.12.3.f3BB

### TNO version

1.3.0a

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, LAR, NSB, BBA

### Describe the GFX issue

Kanwal Singh is his own head of government, however this uses a different portrait.

### Steps to reproduce / Cause of the issue

n/a

### Expected behaviour

That the same portrait would be used for the same person

### Screenshots

![Screenshot (116)](https://user-images.githubusercontent.com/98137316/197285055-a585f88b-30d0-4a04-a74f-402b82e49de7.png)
![Screenshot (117)](https://user-images.githubusercontent.com/98137316/197285093-7d078443-bca2-41e4-9744-6083610302b3.png)

**Comment by runelead00** [comment] 2022-10-21 21:55
Duplicate of #761 You don't have to report the same issue multiple times

**Closed by runelead00** 2022-10-21 21:55 UTC
Labels: GFX/Graphics, Duplicate
