### ISSUE TITLE
The problem with displaying unit models in 3D in the ZRF

### ISSUE THREAD

**Issue by Dwffffffcccccc** [TNODevs/TNO-Bug-Tracker#2713] opened 2023-11-14 15:58 UTC
### Operating System

Windows 11.

### HOI4 version

the latest version of hoi4

### TNO version

the latest version of tno

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

The models of the units are not displayed normally and are completely black.

### Steps to reproduce / Cause of the issue

1. Sit down for the Western Russian Revolutionary Front.

### Expected behaviour

Normal display of units and their uniforms during the game.

### Screenshots

![Screenshot_13](https://github.com/TNODevs/TNO-Bug-Tracker/assets/87900842/8a6828fb-3c92-4cee-8d38-c1dd31441c60)

**Comment by runelead00** [comment] 2023-11-14 21:59
Duplicate of #2522

**Closed by runelead00** 2023-11-14 21:59 UTC
Labels: GFX/Graphics, Duplicate
