### ISSUE TITLE
Komi - Cannot confirm to initiate raid against a neighbouring country ?

### ISSUE THREAD

**Issue by Hasbubu** [TNODevs/TNO-Bug-Tracker#1549] opened 2023-02-05 11:15 UTC
### Operating System

Windows 10

### HOI4 version

Latest

### TNO version

Latest

### Do you have other mods in use?

State Transfer Tool (which does not work)

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

Maybe there's an explanation to that that I cannot find, but I cannot confirm a raid initiation by pressing the button for some reason? After it ran out, nothing happened, therefore it must be a bug. Perhaps it doesn't come from TNO but from HOI4, but who knows?
FYI I had all 6 divisions needed and ready on the border to initiate the raid, so it's not that. All prerequisites were also OK.

### Steps to reproduce / Cause of the issue

1. Play Komi
2. Prepare raid against any neighouring countries (in this case, it's St. George's Order)
3. Sometimes, the button won't initiate a raid.

### Expected behaviour

The button must initiate the raid when pressed

### Screenshots

![image](https://user-images.githubusercontent.com/97235919/216815534-bdddc5db-9649-4be2-ac18-02e8dc7be970.png)

**Comment by runelead00** [comment] 2023-02-05 17:11
Duplicate of issue #1158 from major known bugs lists, reloading the game will fix it

**Closed by runelead00** 2023-02-05 17:11 UTC
Labels: Bug
