### ISSUE TITLE
Germany - Armored car designer is broken

### ISSUE THREAD

**Issue by hoi4fan1234554321** [TNODevs/TNO-Bug-Tracker#3665] opened 2024-11-03 00:11 UTC
### Operating System

Windows 10

### HOI4 version

1.14.10.51f5

### TNO version

1.6.0

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

the scroll wheel does not exist, thus you cannot add alot of the moduals to the Armored Car

### Steps to reproduce / Cause of the issue

1. Open Armored Car Designer
2. Click 'Select Module'

### Expected behaviour

i expected to scoll down to the remaining modules.

### Screenshots

![20241102175850_1](https://github.com/user-attachments/assets/6c27f277-4ba3-4816-8a92-74a27e3f0030)

### Additional information

it only effects Germany, it is fine for other majors like japan.

**Comment by Stormeagle449** [comment] 2024-11-03 09:07
Duplicate of your own issue: #2961

**Closed by Stormeagle449** 2024-11-03 09:07 UTC
Labels: Bug, Duplicate
