### ISSUE TITLE
Paraguay - Missing foreign minister

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#1253] opened 2022-10-21 20:46 UTC
### Operating System

Windows 11

### HOI4 version

1.12.3.f3BB

### TNO version

1.3.0a

### Do you have other mods in use?

no

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, LAR, NSB, BBA

### Describe the GFX issue

Paraguay is missing its foreign minister

### Steps to reproduce / Cause of the issue

n/a

### Expected behaviour

n/a

### Screenshots

![Screenshot (120)](https://user-images.githubusercontent.com/98137316/197285883-e597fc72-eb15-48e9-8627-7941ae8d10ed.png)

**Comment by runelead00** [comment] 2022-10-21 22:01
Duplicate of https://github.com/TNODevs/TNO-Bug-Tracker/issues/863 You don't have to report the same issue multiple times

**Closed by runelead00** 2022-10-21 22:01 UTC
Labels: GFX/Graphics, Duplicate
