### ISSUE TITLE
Germany- Every time a certain event pop up

### ISSUE THREAD

**Issue by Godsofchicken** [TNODevs/TNO-Bug-Tracker#516] opened 2022-01-24 23:33 UTC
**Questions**

- Operating System: GeForce Now
- HOI4 Version: 1.11- Most recent Version 
- TNO Version:  Most recent one 
- Any other mods in use: 2WR
- Were you using Steam? Yes
- Which expansions do you NOT have? I have all expansions beside unit packs, speeches, etc.

**Longer Description of Issue:**
Was playing Novosibirsk until my game kept crashing, heard about some bug with Goring's Germany and tag switched over to them. When the event the "The first promotions" occurs the game freezes and crash

**Steps to Reproduce/Cause Issue:**

1. Trigger "The first promotions" event

2. Press the button, then it crashes

etc...

**Screenshots:**

**Comment by masterbobli** [comment] 2022-01-25 17:56
Duplicate of #495 , has been fixed in dev build.

**Closed by masterbobli** 2022-01-25 17:56 UTC
Labels: Crash, Duplicate
