### ISSUE TITLE
Novosibirsk - Short Description of Issue

### ISSUE THREAD

**Issue by fallettaItaliano** [TNODevs/TNO-Bug-Tracker#2974] opened 2024-02-17 20:07 UTC
### Operating System

Windos 10

### HOI4 version

1.13.6

### TNO version

1.5.0

### Do you have other mods in use?

"the second west russian war" - "economic cheat" - "colored railways" - "radio TNO: music of the new order" - "radio TNO: music of the liberal china" - "the new order: last waltz expanded" - "the new order: GDP+sociatal development cheats".

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

i don't know why but i can't raid neighbor countries even if the requirements are fullfilled. Any ideas?

### Steps to reproduce / Cause of the issue

1 go to decisons
2 try to raid
3 the button wouldn't give me the possibility to do it (the button was not "bright".

### Expected behaviour

i want to raid other countries

### Screenshots

![Immagine 2024-02-17 152146](https://github.com/TNODevs/TNO-Bug-Tracker/assets/160356704/200cfe98-32eb-4149-b54b-57665161dd9c)

**Comment by runelead00** [comment] 2024-02-17 20:09
Duplicate of #1158 reload your save and it should work

**Comment by fallettaItaliano** [comment] 2024-02-17 23:31
thank you very much! but it doesn't work. any other solutions?

**Closed** 2024-02-25 03:24 UTC
Labels: Bug, Duplicate
