### ISSUE TITLE
Paraguay - Missing foreign minister

### ISSUE THREAD

**Issue by GeneralLemarc** [TNODevs/TNO-Bug-Tracker#770] opened 2022-03-20 06:47 UTC
**Questions**

- HOI4 Version: current
- TNO Version: current
- Any other mods in use: 2WRW and US elections GUI

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**
![Screenshot (2736)](https://user-images.githubusercontent.com/98137316/159151501-f4c8b374-0e4a-46d0-b044-3800794b49e2.png)

**Comment by runelead00** [comment] 2022-10-21 22:01
Duplicate of https://github.com/TNODevs/TNO-Bug-Tracker/issues/863

**Closed by runelead00** 2022-10-21 22:01 UTC
Labels: GFX/Graphics, Duplicate
