### ISSUE TITLE
Collab England - No way to combat US/GER influence

### ISSUE THREAD

**Issue by ParadiseZhen19** [TNODevs/TNO-Bug-Tracker#306] opened 2021-11-25 06:03 UTC
**Questions**

- Operating System: Win 11
- HOI4 Version: 1.10.8
- TNO Version: 1.2
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have? Battle for Bosphorous, No Steps Back

**Longer Description of Issue:**When I play Collab England as Macmillian, I find that I cannot combat either OFN/Pact influence, beacuse it is said that England's influence will increase 3 per month, but it did't happen, while OFN/Pact can increase their influence as it says. As the screenshot says, its Apr 1967 but England' influence is just 18.

**Steps to Reproduce/Cause Issue:**

1.Play England, win the ECW as Collab Government
2. Win the election as Macmillian
3. Finish the focus tree and Enter the "Altantic Battleground" 

**Screenshots:**
![image](https://user-images.githubusercontent.com/77340634/143387906-f55ee02f-5d1b-4757-b1e8-ec7e35a9b6f4.png)

**Comment by ParadiseZhen19** [comment] 2021-11-25 06:04
Btw, in the economy system, when my inflation goes up, I can't print money, I click the button but it did't work

**Comment by masterbobli** [comment] 2021-12-02 05:53
The issue is a duplicate of #237 .

**Closed** 2021-12-02 05:54 UTC
Labels: Bug
