### ISSUE TITLE
BRY - Back on the World Stage focus issue

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3356] opened 2024-06-27 10:16 UTC
### Operating System

Windows 10

### HOI4 version

1.14.6

### TNO version

1.5.0d

### Do you have other mods in use?

TNO Tool Mod

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

In the regional stage, Sablin can get the BRY.90 event in the focus "Back on the World Stage" even if Britain is fascist/natsoc. It has zero sense for obvious reasons.

### Steps to reproduce / Cause of the issue

Should Buryatia unites Far East and complete the focus "Back on the World Stage".

### Expected behaviour

Sablin should get this event if Britain is socialist (not fascist/natcos at least).

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/0e29bd30-a2ee-454f-a6d6-6ea1c35984c3)

**Comment by Stormeagle449** [comment] 2024-06-28 09:04
Duplicate of #2936

**Closed by Stormeagle449** 2024-06-28 09:04 UTC
Labels: Bug, Duplicate

**Comment by Marok132** [comment] 2024-06-28 14:39
> Duplicate of #2936

Will Sablin get this event if Joyce or other fascists are in charge yet? I didn't get an answer on my question.
