### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by slugjug1337** [TNODevs/TNO-Bug-Tracker#2676] opened 2023-11-11 22:27 UTC
### Operating System

Windows 11

### HOI4 version

1.13.5

### TNO version

1.5.0b "The Ruin"

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/13326607/error.log)

I cant upload the save file it said it doesnt accept the file type

### Describe the GFX issue

WRRF Soldiers look black void but the light inf unit model looks perfectly fine

### Steps to reproduce / Cause of the issue

1. Go to play WWRF
2. Zoom into the unit model
3. In template editor it shows normal units as a blacked out model

### Expected behaviour

I saw black unit models with broken models

### Screenshots

![20231111172547_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/150543818/d8f11545-1069-4cbd-86f2-0f6bf09c4a75)
![20231111172601_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/150543818/7741a280-0350-4adc-a9ee-2aaa3a3fa8bb)
![20231111172606_1](https://github.com/TNODevs/TNO-Bug-Tracker/assets/150543818/90f30152-5bd9-44fe-917e-37f35e0f81f3)

### Additional information

I tried turning all DLCS off, i un installed and re installed the game, i tried to validate steam files and the issue stayed,  this issue didnt appear for any of the other warlords for me

**Comment by runelead00** [comment] 2023-11-12 02:40
Duplicate of #2522

**Closed by runelead00** 2023-11-12 02:40 UTC
Labels: GFX/Graphics
