### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by Dwffffffcccccc** [TNODevs/TNO-Bug-Tracker#3046] opened 2024-03-09 06:05 UTC
### Operating System

Windows 11.

### HOI4 version

the latest version of hoi4

### TNO version

the latest version of tno

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

3d VRRF units are not displayed in their normal form and have lost their textures.

### Steps to reproduce / Cause of the issue

1. Go to HOI4 and play for the VRRF.

### Expected behaviour

Units models must have textures

### Screenshots

![Uploading Screenshot_14.png…]()

**Comment by runelead00** [comment] 2024-03-09 07:11
Duplicate of #2522

**Closed by runelead00** 2024-03-09 07:11 UTC
Labels: GFX/Graphics, Duplicate
