### ISSUE TITLE
United States of Siberia- CTD when capitulating WAU

### ISSUE THREAD

**Issue by ThirdEdition** [TNODevs/TNO-Bug-Tracker#395] opened 2021-12-11 08:02 UTC
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8
- TNO Version: v1.2.0d “Toolbox Theory”
- Any other mods in use: Radio TNO: Music of the New Order
- Were you using Steam? Yes
- Which expansions do you NOT have? No Step Back

**Longer Description of Issue:**
Was playing as the United States of Siberia, used mercenary mechanic to send 4 volunteers to Liberia for the Mano War.  Managed to beat most of the West African Alliance's members. The CTD occurs when I capitulate the West African Union itself.

**Steps to Reproduce/Cause Issue:**

1. Send volunteers to Liberia

2. Capitulate the WAU

etc...

**Screenshots:**
The game crashed so I couldn't take a screenshot.

**Game Saves and Log Files, if possible:**
An autosave a bit before the capitulation:
[SaveGame.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/7696650/SaveGame.zip)

**Comment by runelead00** [comment] 2022-07-03 06:20
Duplicate of #305

**Closed by runelead00** 2022-07-03 06:20 UTC
Labels: Crash, Duplicate
