### ISSUE TITLE
Magadan - Unable to launch raids against warlords

### ISSUE THREAD

**Issue by goose-5810** [TNODevs/TNO-Bug-Tracker#484] opened 2022-01-22 22:47 UTC
**Questions**

- Operating System:
- HOI4 Version: Newest patch
- TNO Version: Newest (NSB rework)
- Any other mods in use: 2nd West Russian War mod
- Were you using Steam? Yes
- Which expansions do you NOT have?
Together for Victory, Man the Guns, La Resistance
**Longer Description of Issue:**
As Magadan, I can't launch raids against a warlord. I've tested it on both Amur and Yakutia and both don't work 
**Steps to Reproduce/Cause Issue:**

1. Play as Magadan

2. Launch raid against a warlord 

etc...

**Screenshots:**
not really applicable

**Comment by Nukola16** [comment] 2022-05-01 01:27
The description isn't clear enough, but if it's useful I've seen that after preparing the raid the time limited decision to launch the raid sometimes gets bugged: even if conditions are OK, clicking on it does nothing.
I solved it by saving and reloading. That way it works.

**Comment by runelead00** [comment] 2023-02-07 02:48
Duplicate of an issue now included in known bugs list, closing this instance

**Closed by runelead00** 2023-02-07 02:48 UTC
Labels: Bug, Duplicate
