### ISSUE TITLE
Free England (Post Civil War) - Crash upon first election of SLP

### ISSUE THREAD

**Issue by Studwick** [TNODevs/TNO-Bug-Tracker#578] opened 2022-01-30 13:12 UTC
**Questions**

- Operating System: Windows 10 x86_64

- HOI4 Version: 1.11.5
- TNO Version: 1.2.1a
- Any other mods in use: TNO Music Mod
- Were you using Steam? Yes
- Which expansions do you NOT have? Have all

**Longer Description of Issue:**
Game crashes after the event "The Decision of a Free People" when it results in a SLP victory.
The background can keep running when not resolving the event, and it results in a CTD upon the first 24h tick after selecting the option "The Socialist Labour Party wins the election!". 

I can lead the NLD to victory in the same save and it does not cause a crash (though it leads to a generic HoS and no Jellicoe, likewise reported in [this bug report](https://github.com/TNODevs/TNO-Bug-Tracker/issues/500))

**Steps to Reproduce/Cause Issue:**

1. Win the civil war as HMMLR

2. Campaign and win as the SLP

**Game Saves and Log Files, if possible:**
[hoi4_20220130_140358.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/7965945/hoi4_20220130_140358.zip)

[SLP Victory.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/7965948/SLP.Victory.zip)

**Comment by Studwick** [comment] 2022-01-30 22:32
Somewhat ended up solving it myself. 

For the SLP crash it seems like the following immediate command in event ENG_Government_Changes.2 is causing the crash

> immediate = { 
>         log = "[GetDateText]: [Root.GetName]: event ENG_Government_Changes.2" 
>         remove_advisor_role = {
>             character = FEN_Reg_Birch
>             slot = economy_minister
>         }
>         add_advisor_role = {
>             character = FEN_Reg_Birch 
>             advisor = {
>                 slot = head_of_government
>                 cost = 50
>                 idea_token = ENG_Reg_Birch_hog
>                 traits = {
>                     hog_ambitious_union_boss
>                 }
>                 allowed = {
>                     original_tag = ENG
>                 }
>             }
>         }
>     }

Deleting that section seems to have stopped it from causing a CTD. Not exactly sure why, but then again i am not that code-savy. 

As for the lack of Jellicoe as HoS, that seems to be because as the code stands he isn't being created as a country_leader in ENG_Government_Changes.1 and ENG_Government_Changes.2. You need to add the following

> 			create_country_leader = {
> 				name = "George Jellicoe"
> 				desc = "POLITICS_GEORGE_JELLICOE_DESC"
> 				picture = "Portrait_England_George_Jellicoe.dds"
> 				expire = "1990.1.1"
> 				ideology = conservative_democracy_subtype
> 				traits = { son_of_admiralty }
> 			}

That is still leaving some issues that the FEN ministers are not being added properly (besides the ENG_Generic_Vacant_for). Will look into what the issue is there

**Comment by Studwick** [comment] 2022-01-31 00:11
So, running it through debug, it seems like there is something wrong with the FEN ministers that get added post election. 
This could also be the reason why Reg Birch seems to crash ENG_Government_Changes.2 with the immediate command. 

Trying to pop both ENG_Government_Changes.1 and 2 results in variants of this error

>[effectimplementation.cpp:1747]: events/TNO_England.txt:17116: add_ideas: Invalid idea: ENG_Shirley_Williams_eco. If you wanted to reference a variable, you need to explicitly prefix it with var: or temp_var:

In this case we can just replace Shirley Williams with any other FEN minister both from NDL and SLP and the error is the same. 

I tried switching out Thatcher ministers from ENG_Government_Changes.3 with some of the FEN ones making errors (pretty cursed having Francis Pym becoming foreign minister under the SLP) with the result that the minister gets assigned correctly. So i don't think the issue is with the events in TNO_England. 

I tried looking into "Reich - England and Free England.txt" in the characters folder, but couldn't really figure it out.

**Comment by tkgitno** [comment] 2022-01-31 03:45
Should be fixed now, thx for reporting

**Closed by tkgitno** 2022-01-31 03:45 UTC
Labels: Crash

**Comment by Studwick** [comment] 2022-01-31 07:44
@tkgitno 
You wouldn't happen to be able to describe how you fixed it, so i can apply the same fix to my game rather than wait for the next hotfix?

That and i would love to learn what was wrong, for the sake of learning about modding and HoI4 code.

**Comment by tkgitno** [comment] 2022-01-31 14:02
So basically the crash is caused by using _remove_advisor_role_ for Econmin Birch (FEN_Reg_Birch_eco) before removing him from the cabinet, therefore the game can't identify the data correctly and breaking the save.
Simply just delete the _remove_advisor_role_ part in the event will solve it - this effect shouldn't be used to replace ministers anyway bar a few exceptions. Rather, _remove_ideas_ / _remove_all_ministers_ and _add_ideas_ alone are sufficient.

The other non-CTD bugs are either caused by coding in the wrong character tokens (ENG_David_Eccles_hog is the character definied in the file but ENG_David_Eccles is recruited instead) or not using _add_advisor_role_ for the character who should be minister (FEN_Bill_Alexander_sec is missing hence he can't show up as security minister after SLP 1st election). And yes if the characters aren't recruited in history file they'll cause bugs when we want to use them for ministers since this can only be initialized at game start.

**Comment by Velvetgoat22** [comment] 2022-02-07 04:20
> So basically the crash is caused by using _remove_advisor_role_ for Econmin Birch (FEN_Reg_Birch_eco) before removing him from the cabinet, therefore the game can't identify the data correctly and breaking the save. Simply just delete the _remove_advisor_role_ part in the event will solve it - this effect shouldn't be used to replace ministers anyway bar a few exceptions. Rather, _remove_ideas_ / _remove_all_ministers_ and _add_ideas_ alone are sufficient.
> 
> The other non-CTD bugs are either caused by coding in the wrong character tokens (ENG_David_Eccles_hog is the character definied in the file but ENG_David_Eccles is recruited instead) or not using _add_advisor_role_ for the character who should be minister (FEN_Bill_Alexander_sec is missing hence he can't show up as security minister after SLP 1st election). And yes if the characters aren't recruited in history file they'll cause bugs when we want to use them for ministers since this can only be initialized at game start.

I tried removing Remove_advisor but it just stopped the event from working at all
