### ISSUE TITLE
Germany - The "An Atlantic Battleground" proxy is missing localization and doesn't seem to work

### ISSUE THREAD

**Issue by MadTaco** [TNODevs/TNO-Bug-Tracker#2064] opened 2023-07-04 04:48 UTC
### Operating System

Windows 10

### HOI4 version

Avalanche v1.12.14.50e7 (5555)

### TNO version

v1.4.1d "Ugly American"

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

![eng](https://github.com/TNODevs/TNO-Bug-Tracker/assets/132858608/468eb7ba-6432-455d-88ad-72f6b56f11e4)

### Describe the bug

The proxy/mechanic for "An Atlantic Battleground" to get England to join the OFN or Pakt is missing localization and doesn't ever seem to end.

### Steps to reproduce / Cause of the issue

Played as Germany and kept doing the decisions for about one year with no outcome or end. Seems to have been caused by the Foreign Policy GUI update.

### Expected behaviour

Localization to appear and scenario to eventually resolve.

### Screenshots

![eng](https://github.com/TNODevs/TNO-Bug-Tracker/assets/132858608/37847468-34a7-453a-b3cf-7aa8c1ad04e0)

### Additional information
[Saves.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/11944506/Saves.zip)

_No response_

**Comment by AcornSap** [comment] 2023-07-04 16:27
I have been having this bug too, hopefully they fix it soon.

**Comment by Stormeagle449** [comment] 2023-07-04 16:29
Duplicate of https://github.com/TNODevs/TNO-Bug-Tracker/issues/1957, already fixed in Dev Build

**Closed by Stormeagle449** 2023-07-04 16:29 UTC
Labels: Localization
