### ISSUE TITLE
Japan - CTD when loading a Peace Conference

### ISSUE THREAD

**Issue by CaptEric20000** [TNODevs/TNO-Bug-Tracker#574] opened 2022-01-30 01:01 UTC
**Questions**

- Operating System: Windows 10
- HOI4 Version:1.11.5
- TNO Version:1.2.1a
- Any other mods in use: N/A
- Were you using Steam? Yes
- Which expansions do you NOT have? I have all of them

**Longer Description of Issue:**
When i was playing Japan. I was focusing on the events and Focus tree for it. I went with Tagkai. But a few days after 1966/03/20 it tells me loading Peace Conference then peocess
 to CTD. I am not sure which war it is and I am not in a active war.  

Can contact me on discord here if more information is needed. Canadian001#1481
**Steps to Reproduce/Cause Issue:**

1.play japan to around 1966/03/20

2.it starts loading peace conferece then CTD

etc...

**Screenshots:**

**Game Saves and Log Files, if possible:**

[JAP_1966_03_20_01.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/7965081/JAP_1966_03_20_01.zip)

**Comment by tkgitno** [comment] 2022-02-01 08:49
Fixed in Dev Build (it's caused by the West African War which's somehow extremely performance-heavy due to how Paradox makes peace deal work)

**Closed by tkgitno** 2022-02-01 08:49 UTC
Labels: Crash
