### ISSUE TITLE
West Russian Revolutionary Front, comitern vote is hung

### ISSUE THREAD

**Issue by ChrDur1** [TNODevs/TNO-Bug-Tracker#3592] opened 2024-09-07 06:06 UTC
### Operating System

Windows 11

### HOI4 version

1.14.7 or 1.14.8

### TNO version

1.6 SFFG

### Do you have other mods in use?

Second West russian war

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

MTG, LAR, NSB, BBA, AAT, TOA

### Files

[Soviet 2WRW.zip](https://github.com/user-attachments/files/16914989/Soviet.2WRW.zip)

### Describe the bug

In the Communist Internationale, a vote hasn't passed and its been hung for almost one in-game year.

### Steps to reproduce / Cause of the issue

1. go to decisions tab
2. Scroll to Communist international
3. see error

### Expected behaviour

The resolution should pass without hang

### Screenshots

![Screenshot 2024-09-06 235923](https://github.com/user-attachments/assets/cfdbabf7-50b7-4898-98f3-f925c8b7d85e)

### Additional information

d

**Comment by Stormeagle449** [comment] 2024-09-07 20:39
Did you annex Tyumen in your game?

**Comment by Stormeagle449** [comment] 2024-09-18 09:23
I can see from your save file that you annexed Tyumen before the vote finished, ergo this issue is a duplicate of #2107, already fixed on Dev Build.

**Closed by Stormeagle449** 2024-09-18 09:23 UTC
Labels: Bug, Duplicate
