### ISSUE TITLE
Comintern - Leader doesn't get replaced

### ISSUE THREAD

**Issue by BMBKHNK** [TNODevs/TNO-Bug-Tracker#3065] opened 2024-03-13 12:18 UTC
### Operating System

windows 11

### HOI4 version

1.14.1

### TNO version

 1.5.0b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

it don’t support 

### Describe the bug

Comintern stuck forever bug 
general election count down  doesn't show up.

### Steps to reproduce / Cause of the issue

1.leader country of comintern got annex 
2.comintern vote stuck 
3. general election count down  doesn't show up.

### Expected behaviour

second powerfull country Next to leader country take the position to be new leader

### Screenshots

![Screenshot (1404)](https://github.com/TNODevs/TNO-Bug-Tracker/assets/163300654/d487f0bc-77fd-4ef6-a6d0-5562a97d94f9)

**Comment by runelead00** [comment] 2024-07-05 19:48
Duplicate of #2107

**Closed by runelead00** 2024-07-05 19:48 UTC
Labels: Bug

**Comment by Marok132** [comment] 2024-07-05 20:05
> Duplicate of #2107

Is this bug fixed in dev build?
