### ISSUE TITLE
Siberian Soviet Socialist Republic (Irktusk) - Not enough preparadness available to strike Russian Republic

### ISSUE THREAD

**Issue by Nukola16** [TNODevs/TNO-Bug-Tracker#853] opened 2022-04-30 23:39 UTC
### Operating System

Windows 10

### HOI4 version

Barbarossa 1.11.10.29f3

### TNO version

v1.2.1c

### Do you have other mods in use?

No

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[error.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/8597999/error.log)
[game.log](https://github.com/TNODevs/TNO-Bug-Tracker/files/8598012/game.log)

### Describe the bug

I cannot reach the needed 75 preparadness because, after I select all the related decisions to prepare for war, the preparadness is just 65 and I cannot take any more decisions in order to reach 75.

### Steps to reproduce / Cause of the issue

1. Go to country decisions
2. Go to The Russian Reunification War subsection
3. There are no decisions that could be taken except "Strike Russia" which is unavaiable due to low points

POSSIBLE CAUSES

1. Might be the Russian Republic
2. I clicked all the possible buttons at once 

### Expected behaviour

Reaching 75 with all the decisions or having more decisions to select from to reach 75

### Screenshots

![Cant start Russian Reunification War](https://user-images.githubusercontent.com/104684619/166126100-d8024fe3-9ac2-453a-aca9-d7071355cf1a.jpg)

**Comment by runelead00** [comment] 2022-05-11 20:21
While I'm not entirely certain of the cause, I believe the issue is fixed in Dev Build

**Closed by runelead00** 2022-05-11 20:21 UTC
Labels: Bug
