### ISSUE TITLE
USA - When Harrington became president,Harrington's Popularity is 0

### ISSUE THREAD

**Issue by otherside02** [TNODevs/TNO-Bug-Tracker#1484] opened 2023-01-14 02:50 UTC
### Operating System

Windows10

### HOI4 version

1.12.7

### TNO version

v1.3.0e

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

When Harrington became president,Harrington's Popularity is 0. 
All classes hated his reforms.
Everyone was angry with him.

### Steps to reproduce / Cause of the issue

1.Start the game as USA
2..Play Harrington

### Expected behaviour

To get Harrington's popularity back to normal

### Screenshots

![20230114103354_1](https://user-images.githubusercontent.com/46292981/212447232-8071a2aa-5bd0-4547-a1d6-bc8c27c924c1.jpg)
![20230114103356_1](https://user-images.githubusercontent.com/46292981/212447234-554adf1f-9013-450b-8b0d-eba438744752.jpg)

**Comment by runelead00** [comment] 2023-01-14 04:38
Should be fixed in Dev Build, caused by US election code which is an ungodly creature

**Closed by runelead00** 2023-01-14 04:38 UTC
Labels: Bug
