### ISSUE TITLE
IBR - Start focus tree nukes colony GDP

### ISSUE THREAD

**Issue by MrStraws114514** [TNODevs/TNO-Bug-Tracker#2983] opened 2024-02-21 08:04 UTC
### Operating System

Windows 11

### HOI4 version

1.13.6

### TNO version

1.5.0b

### Do you have other mods in use?

None

### Were you using Steam?

No

### Which major expansions do you NOT have?

I have all

### Describe the bug

![6V8@D{_FHNKFLFWZX 7XC(Y](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/b0f41f21-278b-4422-bc9c-cda9e265b38e)
here's code of Algeria part
![_%)_}OO)3SGV66A8A1(50O4](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/496ba14e-0e5d-4e6e-8a8a-ca648363bf0b)
![(6PA{U$Q$DQ X BKYEP DTC](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/be586bd9-458c-473f-b2d5-8e052ce2e03e)
in 2nd screenshot, it gonna multiply GDP with 
var state_value_multiplier_temp
but the focus didnt set this var, it wrongly set temp_state_value_addition instead
and this'll make local GDP nuked
![S2U{@6%2T20Z1PV{$FN~ @S](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/a179351a-160f-497c-a0e8-24125424935e)
![V{AYU Y830@%RN{CJI1P0 3](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/731b9301-78ae-4945-90dc-fa90a70373e5)
this also happen on 2 other colony focus

### Steps to reproduce / Cause of the issue

here's way to fix
in file tno - common - national_focus - tno_lberia_shared
replace temp_state_value_addition with state_value_multiplier_temp
for IBR_Matters_Beyond_Sahara, IBR_Ventures_Algeria, IBR_Business_Morocco

after replace:
![1@}S0_0H_V%V` LK{~QL7JQ](https://github.com/TNODevs/TNO-Bug-Tracker/assets/142401995/1d092952-58f4-47be-bed1-14d042021f83)

### Expected behaviour

start focus no longer nukes local GDP

**Comment by runelead00** [comment] 2024-02-21 08:24
Duplicate of #2960

**Closed by runelead00** 2024-02-21 08:24 UTC
Labels: Bug, Duplicate
