### ISSUE TITLE
Iberia - Sevilla lore still mentions Gibraltar Dam 

### ISSUE THREAD

**Issue by 15persons** [TNODevs/TNO-Bug-Tracker#1661] opened 2023-03-17 16:54 UTC
### Operating System

Windows 10

### HOI4 version

Avalanche v.1.12.11.137b (12ff) (D) (S)

### TNO version

TNO v1.4.0a - Silicon Dreams 

### Do you have other mods in use?

Vanilla Toolpack

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

The bug is the lore of Sevilla being outdated in TNO's current state due to new lore. 

### Steps to reproduce / Cause of the issue

1. Click on Sevilla state
2. Open up state lore
3. Read the 2nd sentence in the lore

### Expected behaviour

I expected the Gibraltar Dam to not be mentioned.

**Comment by Stormeagle449** [comment] 2023-03-17 17:40
Duplicate ofhttps://github.com/TNODevs/TNO-Bug-Tracker/issues/1582 you don't have to report the same issue multiple times.

**Closed by Stormeagle449** 2023-03-17 17:40 UTC
Labels: Bug, Duplicate
