### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by Manchesterist** [TNODevs/TNO-Bug-Tracker#1459] opened 2022-12-12 21:52 UTC
### Operating System

Windows 10

### HOI4 version

 Patch 1.12.4

### TNO version

TNO v1.3.0b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

[21:28:21][pdx_lua.cpp:527]: 
LUA Error: incorrect lua value: SELECTION_HOVERED_STATE_COLOR_INDEX_CONTROLLED
[21:28:21][pdx_lua.cpp:527]: 
LUA Error: incorrect lua value: SELECTION_HOVERED_STATE_COLOR_INDEX_FOREIGN
[21:28:22][pdx_audio.cpp:1305]: Music with name 'maintheme' already added
[21:28:22][assetfactory_audio.cpp:576]: SoundEffect '' does not have a category assigned
[21:28:37][texturehandler.cpp:216]: Couldn't find texture file: ''
[21:28:49][pdxassetutil.cpp:339]: Failed to create material with shader PdxMeshAdvancedAnim
[21:29:06][database_scoped_variables.h:62]: invalid database object for effect/trigger:  file: music/0_radio_new_york.txt line: 9 social_democracy. use var:var_name to explicitly use variables in effects/triggers
[21:29:06][database_scoped_variables.h:62]: invalid database object for effect/trigger:  file: music/0_radio_new_york.txt line: 14 social_democracy. use var:var_name to explicitly use variables in effects/triggers
[21:29:06][pdx_audio.cpp:1368]: Could not find music named dance_your_troubles_away
[21:29:06][pdx_audio.cpp:1368]: Could not find music named from_glen_to_glen
[21:29:06][pdx_audio.cpp:1368]: Could not find music named the_man_on_the_british_countryside
[21:29:06][pdx_audio.cpp:1368]: Could not find music named winter_came_spring
[21:29:06][pdx_audio.cpp:1368]: Could not find music named allies_justanotherday
[21:29:06][pdx_audio.cpp:1368]: Could not find music named allies_longingfortomorrow
[21:29:06][pdx_audio.cpp:1368]: Could not find music named allies_meetingwithcigars
[21:29:06][pdx_audio.cpp:1368]: Could not find music named allies_neverlookingbackagain
[21:29:06][pdx_audio.cpp:1368]: Could not find music named allies_somedaywewillmeetagain
[21:29:06][pdx_audio.cpp:1368]: Could not find music named allies_thenightbefore
[21:29:06][pdx_audio.cpp:1368]: Could not find music named allies_thethoughtofyou
[21:29:06][pdx_audio.cpp:1368]: Could not find music named allies_verylastofgoodbyes
[21:29:06][pdx_audio.cpp:1368]: Could not find music named londoninflames
[21:29:06][pdx_audio.cpp:1368]: Could not find music named operationcompas
[21:29:06][pdx_audio.cpp:1368]: Could not find music named heroesofelalamein
[21:29:06][pdx_audio.cpp:1368]: Could not find music named darkisthenight
[21:29:06][pdx_audio.cpp:1368]: Could not find music named drumbun
[21:29:06][pdx_audio.cpp:1368]: Could not find music named hymnoftheussr
[21:29:06][pdx_audio.cpp:1368]: Could not find music named lilimarlenesolo
[21:29:06][pdx_audio.cpp:1368]: Could not find music named matrosenlied
[21:29:06][pdx_audio.cpp:1368]: Could not find music named mypierwszabrygada
[21:29:06][pdx_audio.cpp:1368]: Could not find music named polishfirstdivision
[21:29:06][pdx_audio.cpp:1368]: Could not find music named romanianpatrioticsong
[21:29:06][pdx_audio.cpp:1368]: Could not find music named soldatenlieder
[21:29:06][pdx_audio.cpp:1368]: Could not find music named trecetibatalioane
[21:29:06][pdx_audio.cpp:1368]: Could not find music named volkhovdrinkingsong
[21:29:06][pdx_audio.cpp:1368]: Could not find music named wachtamrhein
[21:29:06][pdx_audio.cpp:1368]: Could not find music named whitearmyblackbaron
[21:29:06][pdx_audio.cpp:1368]: Could not find music named liberty_equality_fraternity
[21:29:06][pdx_audio.cpp:1368]: Could not find music named imperterrita
[21:29:06][pdx_audio.cpp:1368]: Could not find music named cloak_and_dagger
[21:29:06][pdx_audio.cpp:1368]: Could not find music named a_storm_coming
[21:29:06][pdx_audio.cpp:1368]: Could not find music named claustrophobic_march
[21:29:06][pdx_audio.cpp:1368]: Could not find music named communist_america
[21:29:06][pdx_audio.cpp:1368]: Could not find music named confederate_flags
[21:29:06][pdx_audio.cpp:1368]: Could not find music named democratic_movements
[21:29:06][pdx_audio.cpp:1368]: Could not find music named army_of_the_braves
[21:29:06][pdx_audio.cpp:1368]: Could not find music named bravery_of_the_minority
[21:29:06][pdx_audio.cpp:1368]: Could not find music named march_of_the_defenders
[21:29:06][pdx_audio.cpp:1368]: Could not find music named sacred_war
[21:29:06][musicmanager.cpp:158]: Error no music_station defined for songs in [file] music/radio_tno.txt [location]  file: music/radio_tno.txt line: 8
[21:29:55][containerwindow.cpp:833]: interface/frontendmainview.gui(line 369): Could not find "subscription_position_without_social_gui" in window "mainmenu_social_buttons".
[21:29:56][containerwindow.cpp:833]: interface/frontendmainview.gui(line 218): Could not find "subscription_size" in window "mainmenu_panel_bottom".
[21:29:56][containerwindow.cpp:833]: interface/frontendmainview.gui(line 218): Could not find "version_label_subscription_position" in window "mainmenu_panel_bottom".

### Describe the crash

Crash occurs after the focus titled "No Room for Cowardice" is finished (after the 7 days needed for the focus). This focus is part of the Goering focus tree of Germany, along with many decisions you need to take before declaring war on the Italian Empire (the focus tree "Over the Alps"). I used the cheat "focus.ignoreprerequisites" in order to surpass the problem with the "No Room for Cowardice" focus.

### Steps to reproduce / Cause of the crash

1
2
3
4

**Comment by runelead00** [comment] 2022-12-16 05:34
Should be fixed in Dev Build. You uploaded an error log from loading the game up after the crash which deleted the error log from the crash itself so I'm not entirely sure if I figured out the cause correctly

**Closed by runelead00** 2022-12-16 05:34 UTC
Labels: Crash
