### ISSUE TITLE
WRRF units lack models

### ISSUE THREAD

**Issue by JoeB2505** [TNODevs/TNO-Bug-Tracker#2897] opened 2023-12-20 15:00 UTC
### Operating System

Windows 11

### HOI4 version

1.13.6

### TNO version

1.5.0b

### Do you have other mods in use?

none

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the GFX issue

WRRF units lack models

### Steps to reproduce / Cause of the issue

1. start as west russian revolutionary front
2. zoom in

### Expected behaviour

the units will be black

### Screenshots

![Screenshot 2023-12-20 094824](https://github.com/TNODevs/TNO-Bug-Tracker/assets/101000579/913d9f81-8d68-4a30-a934-8830d68c6e7c)

**Comment by runelead00** [comment] 2023-12-20 20:10
Duplicate of #2522

**Closed by runelead00** 2023-12-20 20:10 UTC
Labels: GFX/Graphics
