### ISSUE TITLE
Yunnan-Near-constant crashes during GAW, issues I have never experienced with any other nation.

### ISSUE THREAD

**Issue by gamerweeb623** [TNODevs/TNO-Bug-Tracker#3438] opened 2024-08-01 01:52 UTC
### Operating System

Windows 11

### HOI4 version

1.14

### TNO version

1.5.0d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Files

I am unable to add files for reasons I can't figure out. 

### Describe the crash

Freezing for a moment and then the crash

### Steps to reproduce / Cause of the crash

Play Yunnan, do GAW as normal

### Additional information

I have a lot of units, which may be causing problems.

**Comment by runelead00** [comment] 2024-08-04 04:45
Duplicate of #3379, will be fixed next update temp solution listed there

**Closed by runelead00** 2024-08-04 04:45 UTC
Labels: Crash
