### ISSUE TITLE
Comecom Breaks if Country Involved in Vote No Longer Exists

### ISSUE THREAD

**Issue by ComradeSmile** [TNODevs/TNO-Bug-Tracker#2174] opened 2023-09-09 17:16 UTC
### Operating System

Windows 10

### HOI4 version

1.12.14

### TNO version

1.4.1d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, NSB, BBA

### Describe the bug

COMECON bugged out after a nation changes names, in my case it's the Arabian Republic under Baath rule.

### Steps to reproduce / Cause of the issue

1. Click on "offer membership to Arabian Republic"
2. They changes into a completely new nation 3 days later
3. COMECON forever stuck at voting screen

### Expected behaviour

Was expecting it to cancels/updates to new version of such country.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/144553422/9a26f4b5-6d1e-4988-8fbb-948f89ccffb9)

**Comment by runelead00** [comment] 2023-12-13 06:42
duplicate of #2107

**Closed by runelead00** 2023-12-13 06:42 UTC
Labels: Bug, Duplicate
