### ISSUE TITLE
Crash on Selecting Deployment Location

### ISSUE THREAD

**Issue by Mollaser** [TNODevs/TNO-Bug-Tracker#512] opened 2022-01-24 19:42 UTC
**Questions**

- Operating System: Windows 11
- HOI4 Version: 1.11.0
- TNO Version: TNO 1.2.1 Toolbox Theory NSB update
- Any other mods in use: no
- Were you using Steam: Yes
- Which expansions do you NOT have: I have them all

**Longer Description of Issue:**
Whenever I click the button to show where I can deploy trained divisions, the game crashes.

**Steps to Reproduce/Cause Issue:**

1. Open recruit and deploy section at the top
2. train a division

3. 
![image](https://user-images.githubusercontent.com/98353151/150852667-c9ffa644-0651-48f5-94fd-5bef865a31e4.png)
when you click this button the game freezes then crashes.

etc...

**Screenshots:**

**Game Saves and Log Files, if possible:**
cant

**Comment by wariacix** [comment] 2022-02-10 16:06
got it as well, any idea about how to solve it? :(

**Comment by Stormeagle449** [comment] 2022-12-01 10:33
Duplicate of https://github.com/TNODevs/TNO-Bug-Tracker/issues/667, most likely fixed already.

**Closed by Stormeagle449** 2022-12-01 10:33 UTC
Labels: Crash, Duplicate
